#!/usr/bin/env python3
"""Convert a gridded SEG-Y model (one trace per x, samples down z) to the RAW
float32 velocity format used by `rtm` (v[ix*nz+iz]) plus its .hdr sidecar.

Written for the AGL Elastic Marmousi models, whose SEG-Y stores X coordinates
multiplied by 1000 with scalco = 0 (see the textual header), so the trace-header
geometry is NOT trustworthy -- pass --dx/--dz explicitly.

Pure standard library: no numpy dependency.
"""
import argparse, array, os, struct, sys

def be16(b, o): return struct.unpack_from('>h', b, o)[0]

def ibm_block_to_float(raw, count, step):
    """Decode `count` IBM/370 float32 values taken every `step` samples."""
    ints = array.array('I')
    ints.frombytes(raw)
    if sys.byteorder == 'little':
        ints.byteswap()
    out = array.array('f', bytes(4 * count))
    for j in range(count):
        v = ints[j * step]
        if v == 0:
            continue
        frac = v & 0x00FFFFFF
        if frac == 0:
            continue
        x = (frac / 16777216.0) * (16.0 ** (((v >> 24) & 0x7F) - 64))
        out[j] = -x if (v >> 31) else x
    return out

def ieee_block_to_float(raw, count, step):
    f = array.array('f')
    f.frombytes(raw)
    if sys.byteorder == 'little':
        f.byteswap()
    return array.array('f', [f[j * step] for j in range(count)])

def main():
    p = argparse.ArgumentParser()
    p.add_argument('segy')
    p.add_argument('out')
    p.add_argument('--dx', type=float, required=True, help='trace spacing in the FILE, metres')
    p.add_argument('--dz', type=float, required=True, help='sample spacing in the FILE, metres')
    p.add_argument('--decimate-x', type=int, default=1)
    p.add_argument('--decimate-z', type=int, default=1)
    p.add_argument('--ox', type=float, default=0.0)
    p.add_argument('--oz', type=float, default=0.0)
    p.add_argument('--vmin-clip', type=float, default=1450.0,
                   help='floor applied after decimation (the reader rejects v<=0)')
    p.add_argument('--vmax-clip', type=float, default=20000.0)
    a = p.parse_args()

    size = os.path.getsize(a.segy)
    with open(a.segy, 'rb') as f:
        f.seek(3200)
        bh = f.read(400)
        ns, fmt = be16(bh, 20), be16(bh, 24)
        bps = 2 if fmt == 3 else 4
        if fmt not in (1, 5):
            raise SystemExit('only SEG-Y formats 1 (IBM) and 5 (IEEE) are supported here')
        trace_bytes = 240 + ns * bps
        ntraces = (size - 3600) // trace_bytes

        nx = (ntraces + a.decimate_x - 1) // a.decimate_x
        nz = (ns      + a.decimate_z - 1) // a.decimate_z
        decode = ibm_block_to_float if fmt == 1 else ieee_block_to_float

        out = open(a.out, 'wb')
        lo, hi, nclip = 1e30, -1e30, 0
        for k in range(nx):
            f.seek(3600 + (k * a.decimate_x) * trace_bytes + 240)
            col = decode(f.read(ns * 4), nz, a.decimate_z)
            for j in range(nz):
                v = col[j]
                if v < lo: lo = v
                if v > hi: hi = v
                if v < a.vmin_clip:
                    col[j] = a.vmin_clip; nclip += 1
                elif v > a.vmax_clip:
                    col[j] = a.vmax_clip; nclip += 1
            out.write(col.tobytes())          # depth is the fastest axis == zfast
        out.close()

    dx, dz = a.dx * a.decimate_x, a.dz * a.decimate_z
    with open(a.out + '.hdr', 'w') as h:
        h.write('# RTM velocity model header (generated by segy_to_raw.py)\n'
                '# source: %s\n' % os.path.basename(a.segy))
        h.write('nx = %d\nnz = %d\ndx = %g\ndz = %g\nox = %g\noz = %g\nlayout = zfast\n'
                % (nx, nz, dx, dz, a.ox, a.oz))

    print('SEG-Y   : %s  (%d traces x %d samples, format %d)' % (a.segy, ntraces, ns, fmt))
    print('decimate: x/%d z/%d  ->  nx=%d nz=%d  dx=%g m dz=%g m' %
          (a.decimate_x, a.decimate_z, nx, nz, dx, dz))
    print('extent  : %g m x %g m' % ((nx - 1) * dx, (nz - 1) * dz))
    print('values  : min=%.1f max=%.1f  (%d clipped into [%.1f, %.1f])' %
          (lo, hi, nclip, a.vmin_clip, a.vmax_clip))
    print('wrote   : %s (+ .hdr)  %d bytes' % (a.out, os.path.getsize(a.out)))

main()
