// =============================================================================
// SYNTHETIC VALIDATION DATA GENERATOR  (Phase 3)
//
// This produces  ***SYNTHETIC VALIDATION DATA***  only — never confuse it with
// real seismic data. It writes:
//     <outdir>/velocity.bin        migration velocity model (float32)
//     <outdir>/velocity.bin.hdr    geometry header
//     <outdir>/shots.bin           modelled shot gathers (RTMS format)
//
// The shots are generated by running the SAME forward propagator used by the
// migration. That is an "inverse crime": it is exactly what you want for
// validating that the pipeline works, and it is NOT a test of imaging accuracy
// against real physics.
// =============================================================================
#include <cmath>
#include <cstdio>
#include <stdexcept>
#include <string>
#include <vector>

#include "benchmark.hpp"
#include "rtm_cpu.hpp"
#include "rtm_factory.hpp"
#include "rtm_io.hpp"

using namespace rtm;

int main(int argc, char** argv) try {
    std::string outdir = "data/synthetic";
    int   nx = 201, nz = 151, nt = 1400, nshots = 4, order = 8, nb = 60;
    float dx = 10.0f, dz = 10.0f, dt = 0.001f, f0 = 12.0f;
    float src_z = 20.0f, rec_z = 20.0f, rec_dx = 20.0f;

    // Optional: model through an EXISTING velocity model instead of the
    // built-in three-layer one. Geometry comes from <path>.hdr unless
    // overridden on the command line, exactly like `rtm --velocity`.
    std::string vel_path, shots_out, engine_name = "cpu";
    io::VelocityHeader vh;
    bool have_nx = false, have_nz = false, have_dx = false, have_dz = false;
    float shot_x0 = -1.0f, shot_dx = -1.0f;   // <0 => spread evenly over the line

    for (int i = 1; i < argc; ++i) {
        const std::string a = argv[i];
        auto next = [&]() -> std::string {
            if (i + 1 >= argc) throw std::runtime_error("missing value after " + a);
            return argv[++i];
        };
        if      (a == "--outdir")     outdir = next();
        else if (a == "--nx")       { nx = std::stoi(next()); have_nx = true; }
        else if (a == "--nz")       { nz = std::stoi(next()); have_nz = true; }
        else if (a == "--dx")       { dx = std::stof(next()); have_dx = true; }
        else if (a == "--dz")       { dz = std::stof(next()); have_dz = true; }
        else if (a == "--nt")         nt = std::stoi(next());
        else if (a == "--dt")         dt = std::stof(next());
        else if (a == "--f0")         f0 = std::stof(next());
        else if (a == "--nshots")     nshots = std::stoi(next());
        else if (a == "--order")      order = std::stoi(next());
        else if (a == "--nb")         nb = std::stoi(next());
        else if (a == "--rec-dx")     rec_dx = std::stof(next());
        else if (a == "--src-z")      src_z = std::stof(next());
        else if (a == "--rec-z")      rec_z = std::stof(next());
        else if (a == "--velocity")   vel_path = next();
        else if (a == "--vel-layout") vh.layout = next();
        else if (a == "--shots-out")  shots_out = next();
        else if (a == "--shot-x0")    shot_x0 = std::stof(next());
        else if (a == "--shot-dx")    shot_dx = std::stof(next());
        else if (a == "--engine")     engine_name = next();
        else throw std::runtime_error("unknown option: " + a);
    }

    // ------------------------------------------------------------------
    // Velocity model: three layers, the second interface dipping, plus a
    // small high-velocity box (a point diffractor test for the migration).
    // ------------------------------------------------------------------
    VelocityModel model;
    if (!vel_path.empty()) {
        // Geometry: sidecar first, then CLI overrides (CLI wins).
        io::VelocityHeader sidecar;
        if (io::read_header_file(vel_path + ".hdr", sidecar)) {
            if (!have_nx) nx = sidecar.nx;
            if (!have_nz) nz = sidecar.nz;
            if (!have_dx) dx = sidecar.dx;
            if (!have_dz) dz = sidecar.dz;
            if (vh.layout == "zfast") vh.layout = sidecar.layout;
            vh.ox = sidecar.ox; vh.oz = sidecar.oz;
        }
        vh.nx = nx; vh.nz = nz; vh.dx = dx; vh.dz = dz;
        model = io::read_velocity_raw(vel_path, vh);
    } else {
        model.grid.nx = nx; model.grid.nz = nz;
        model.grid.dx = dx; model.grid.dz = dz;
        model.v.assign((std::size_t)nx * nz, 1500.0f);

        const float z1 = 400.0f;                   // flat interface, metres
        for (int ix = 0; ix < nx; ++ix) {
            const float x  = ix * dx;
            const float z2 = 900.0f + 0.15f * (x - 0.5f * nx * dx);  // dipping
            for (int iz = 0; iz < nz; ++iz) {
                const float z = iz * dz;
                float v = 1500.0f;
                if (z >= z1) v = 2000.0f;
                if (z >= z2) v = 2500.0f;
                model.v[(std::size_t)ix * nz + iz] = v;
            }
        }
        // Box diffractor: 60 x 60 m at (x = 1200 m, z = 700 m)
        for (int ix = 0; ix < nx; ++ix)
            for (int iz = 0; iz < nz; ++iz) {
                const float x = ix * dx, z = iz * dz;
                if (x >= 1200.0f && x < 1260.0f && z >= 700.0f && z < 760.0f)
                    model.v[(std::size_t)ix * nz + iz] = 2800.0f;
            }

        vh.nx = nx; vh.nz = nz; vh.dx = dx; vh.dz = dz; vh.ox = 0; vh.oz = 0;
        vh.layout = "zfast";
        io::write_velocity_raw(outdir + "/velocity.bin", model);
        io::write_header_file (outdir + "/velocity.bin.hdr", vh);
    }

    // ------------------------------------------------------------------
    // Acquisition geometry: split-spread surface line, all receivers live
    // for every shot.
    // ------------------------------------------------------------------
    const int nrec = (int)((nx - 1) * dx / rec_dx) + 1;
    std::vector<ShotRecord> shots((std::size_t)nshots);
    const float xmax = (nx - 1) * dx;
    for (int is = 0; is < nshots; ++is) {
        ShotRecord& s = shots[(std::size_t)is];
        s.sx = (shot_dx > 0.0f)
                 ? (shot_x0 >= 0.0f ? shot_x0 : 0.0f) + shot_dx * (float)is
                 : xmax * (float)(is + 1) / (float)(nshots + 1);
        s.sz = src_z;
        s.nt = nt; s.dt = dt;
        s.rx.resize((std::size_t)nrec);
        s.rz.assign((std::size_t)nrec, rec_z);
        for (int ir = 0; ir < nrec; ++ir) s.rx[(std::size_t)ir] = ir * rec_dx;
    }

    RTMParams par;
    // Modelling only records traces; the source-wavefield snapshots are never
    // used. store_interval = nt keeps a single snapshot slot, so the GPU
    // engines do not try to allocate nt full snapshots at fine grids.
    par.nb = nb; par.order = order; par.f0 = f0; par.store_interval = nt;
    TimeAxis ta; ta.nt = nt; ta.dt = dt;

    auto engine = make_engine(engine_name);
    engine->setup(model, par, ta);

    const float dt_max = max_stable_dt(model.vmax(), engine->grid(), order);
    const float ppw    = points_per_wavelength(model.vmin(), f0, engine->grid());
    std::printf("MODELLED SHOT GATHERS (inverse crime: same propagator as the migration)\n"
                "  grid %d x %d, dx = %.1f m, dz = %.1f m\n"
                "  vmin = %.0f, vmax = %.0f m/s\n"
                "  dt = %.6f s (max stable %.6f s), nt = %d, T = %.2f s\n"
                "  points per wavelength = %.2f\n"
                "  %d shots, %d receivers each\n\n",
                nx, nz, dx, dz, model.vmin(), model.vmax(),
                dt, dt_max, nt, nt * dt, ppw, nshots, nrec);
    if (dt > dt_max) throw std::runtime_error("chosen dt is unstable");

    Timer t;
    for (int is = 0; is < nshots; ++is) {
        std::printf("  modelling shot %d / %d (sx = %.1f m) ...\n",
                    is + 1, nshots, shots[(std::size_t)is].sx);
        std::fflush(stdout);
        engine->model_shot(shots[(std::size_t)is]);
    }
    const std::string shots_path =
        shots_out.empty() ? (outdir + "/shots.bin") : shots_out;
    io::write_shots_raw(shots_path, shots);

    std::printf("\nmodelling took %.2f s\n"
                "velocity model: %s\n"
                "wrote %s  (%d shots x %d traces x %d samples)\n",
                t.elapsed(),
                vel_path.empty() ? (outdir + "/velocity.bin").c_str()
                                 : vel_path.c_str(),
                shots_path.c_str(), nshots, nrec, nt);
    return 0;
}
catch (const std::exception& e) {
    std::fprintf(stderr, "ERROR: %s\n", e.what());
    return 1;
}